services:
  kafka:
    build: .
    container_name: metro_kafka
    restart: unless-stopped
    ports:
      - "19092:9092"
      - "9093:9093"
    environment:
      - KAFKA_EXTERNAL_IP=localhost
      - KAFKA_EXTERNAL_PORT=19092
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: [ "CMD-SHELL", "/opt/kafka/bin/kafka-broker-api-versions.sh --bootstrap-server localhost:9092 || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  init-topics:
    image: apache/kafka:3.6.1
    container_name: metro_init_topics
    depends_on:
      kafka:
        condition: service_healthy
    command: >
      bash -c "
        sleep 5 &&
        /opt/kafka/bin/kafka-topics.sh --create \
          --topic seat-bookings \
          --bootstrap-server kafka:9092 \
          --partitions 3 \
          --replication-factor 1 \
          --config retention.ms=3600000 \
          --config cleanup.policy=delete \
          --if-not-exists &&
        echo 'Topic ready'"
    restart: "no"

volumes:
  kafka_data:
