services:
  redpanda:
    build: .
    container_name: metro_redpanda
    restart: unless-stopped
    ports:
      - "19092:9092"
      - "9644:9644"
      - "33145:33145"
    environment:
      - REDPANDA_EXTERNAL_IP=localhost
      - REDPANDA_ADVERTISED_PORT=19092
    volumes:
      - redpanda_data:/var/lib/redpanda/data
    healthcheck:
      test: [ "CMD-SHELL", "rpk cluster health --api-urls localhost:9644 || exit 1" ]
      interval: 5s
      timeout: 3s
      retries: 15
      start_period: 15s

  init-topics:
    image: redpandadata/redpanda:v23.3.5
    container_name: metro_init_topics
    depends_on:
      redpanda:
        condition: service_healthy
    command: >
      bash -c "
        sleep 3 &&
        rpk topic create seat-bookings \
          --brokers redpanda:9092 \
          --partitions 3 \
          --topic-config retention.ms=3600000 \
          --topic-config cleanup.policy=delete \
          --replicas 1 || echo 'Topic already exists'"
    restart: "no"

volumes:
  redpanda_data:
