[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "/usr/local/bin/start-kafka.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPort = 9092

[[deploy.tcpProxies]]
port = 9092