#!/bin/bash
set -e

# Detect Railway environment
if [ -n "$RAILWAY_PUBLIC_DOMAIN" ]; then
    EXTERNAL_IP="$RAILWAY_PUBLIC_DOMAIN"
    KAFKA_PORT="${RAILWAY_TCP_PROXY_PORT:-9092}"
    echo "Railway environment detected"
else
    EXTERNAL_IP="${KAFKA_EXTERNAL_IP:-localhost}"
    KAFKA_PORT="${KAFKA_EXTERNAL_PORT:-19092}"
    echo "Local environment detected"
fi

export CLUSTER_ID="Mk3OEYBSD34fcwNTJENDM2"
export KAFKA_NODE_ID=1
export KAFKA_PROCESS_ROLES="broker,controller"
export KAFKA_LISTENERS="INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094"
export KAFKA_ADVERTISED_LISTENERS="INTERNAL://kafka:9092,EXTERNAL://${EXTERNAL_IP}:${KAFKA_PORT}"
export KAFKA_CONTROLLER_LISTENER_NAMES="CONTROLLER"
export KAFKA_CONTROLLER_QUORUM_VOTERS="1@localhost:9094"
export KAFKA_LISTENER_SECURITY_PROTOCOL_MAP="INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
export KAFKA_INTER_BROKER_LISTENER_NAME="INTERNAL"
export KAFKA_AUTO_CREATE_TOPICS_ENABLE="true"
export KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR="1"
export KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR="1"
export KAFKA_TRANSACTION_STATE_LOG_MIN_ISR="1"
export KAFKA_LOG_DIRS="/var/lib/kafka/data"

echo "Advertising External IP to Clients as -> ${EXTERNAL_IP}:${KAFKA_PORT}"

# Hand over to the official Apache Kafka Docker launch script
exec /etc/kafka/docker/run